services:
  apache:
    container_name: apache
    build:
      context: ./apache
      dockerfile: Dockerfile 
    ports:
      - 8080:8080
    networks:
      - network
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - network
    depends_on:
      - apache

networks:
  network:
    driver: bridge
#test
